# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fda66bf025abbe2ea70fc5f2748c077a3d8ea59377013cc3118b03b598218aa96860a474d105829404fe3f7b4237f142c87108e35a13ad3d2fa658421e135af1

test:
  secret_key_base: c16c14951f239e8ee0098c2a84569ba1463a2cb7e295d381d4e6faea546fb560a0c67a41eb62c481bb3a0b2be3d3945d85923d08f4d2aeb2bd40026347affe16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
